In [ ]:
#importing data
import pandas as pd
music_data = pd.read_csv('music.csv')
music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [ ]:
#splitting the data into input and output(X and Y).X is the input data and Y is the output data.
X = music_data.drop(columns=['genre'])
X

    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [ ]:
#Y is the output data which is the genre of the music.
Y = music_data['genre']
Y

0        HipHop
1        HipHop
2        HipHop
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10        Dance
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
Name: genre, dtype: str

In [6]:
#learning and predicting the data using algorithms.In this case we are using Decision Tree Classification algorithm.
#creating a model and fitting the data into the model.
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X,Y)
predictions =model.predict([[21,1],[22,0]])
predictions

/home/kelvin/Projects/ML/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['HipHop', 'Dance'], dtype=object)

In [13]:
#calculating the accuracy of the model using train_test_split method.
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)
model.fit(X_train,Y_train)
score = model.score(X_test,Y_test)
score

1.0

In [ ]:
#model persistence using joblib to save the model for future use.
import joblib
joblib.dump(model, 'music-recommender.joblib')

['music-recommender.joblib']

In [ ]:
#loading the model from the saved file and making predictions.
model = joblib.load('music-recommender.joblib')
predictions = model.predict([[21,1]])
predictions

/home/kelvin/Projects/ML/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['HipHop'], dtype=object)

In [22]:
#visualizing the decision tree 
from sklearn import tree

tree.export_graphviz(model, out_file="music-recommender.dot",
                     feature_names=['age', 'gender'], 
                     class_names=sorted(Y.unique()),
                     label='all',
                     rounded=True,
                     filled=True)